# Cargo.toml

[package]
name = "rtp-midi"
version = "0.1.0"
edition = "2021"
# Přidání build skriptu
build = "build.rs"

[lib]
name = "rtp_midi_lib"
# cdylib je nezbytná pro JNI
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.23", features = ["connect"] }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
log = "0.4"
env_logger = "0.11"
crossbeam-channel = "0.5"
cpal = "0.15"
rustfft = "6.1"
anyhow = "1.0"
ddp-rs = "0.3"
toml = "0.8"
tempfile = "3.10"
ctrlc = "3.4"
reqwest = { version = "0.11", features = ["json", "blocking", "rustls-tls"] }
num-traits = "0.2"
url = "2.5.0"
bytes = "1.0"
libc = "0.2"

# Nové závislosti pro Android a JNI
jni = "0.21.1"
binder = "0.0.2"
android_logger = "0.11.0"

[target.aarch64-linux-android.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dev-dependencies]
mockito = "1.2.0"
url = "2.5.0"
rtp-midi = { path = "." }

