# Sample configuration for Rust MIDI/Audio to WLED/LED service
wled_ip = "192.168.1.100"
ddp_port = 4048
led_count = 60
color_format = "RGB" # or "RGBW"
audio_device = "" # leave empty for default
test_midi_port = 5004
log_level = "info"
signaling_server_address = "ws://127.0.0.1:8080/signaling"
audio_sample_rate = 48000
audio_channels = 2
audio_buffer_size = 1024
audio_smoothing_factor = 0.5
webrtc_ice_servers = ["stun:stun.l.google.com:19302"]

# LED mapping preset: "spectrum" or "vumeter"
mapping_preset = "spectrum"

# Example mapping (uncomment and modify as needed)
# [[mappings]]
# input.AudioBand = { band = "bass", threshold = 0.7 }
# output = [
#     { SetBrightness = { value = 255 } },
#     { SetColor = { r = 255, g = 0, b = 0 } }
# ] 