[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cpal = "0.15"
rustfft = "6.1"
tokio = { version = "1", features = ["full"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
