name: CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  rust:
    name: Rust Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Lint
        run: cargo fmt --all -- --check && cargo clippy --all-targets -- -D warnings
      - name: Build
        run: cargo build --workspace --all-targets
      - name: Test
        run: cargo test --workspace --all-targets
      - name: Upload Rust Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-binaries
          path: target/

  android:
    name: Android Build & Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Build Android App
        run: ./gradlew assembleDebug --no-daemon
        working-directory: android_hub/app
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon
        working-directory: android_hub/app
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android_hub/app/build/outputs/apk/debug/*.apk

  esp32:
    name: ESP32 Firmware Build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build ESP32 Firmware
        run: pio run
        working-directory: firmware/esp32_visualizer
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: firmware/esp32_visualizer/.pio/build/*/*.bin