name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build, Test, Format & Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run linter (Clippy)
      run: cargo clippy -- -D warnings

    - name: Build WASM UI (ui-frontend)
      run: |
        cd ui-frontend
        cargo install wasm-pack --locked || true
        wasm-pack build --target web
        cd ..

    - name: Build for Android (check only)
      run: |
        rustup target add aarch64-linux-android
        cargo build --target aarch64-linux-android --release --features hal_android || true

    - name: Build for ESP32 (check only)
      run: |
        rustup target add xtensa-esp32-none-elf || true
        cargo build --target xtensa-esp32-none-elf --release --features hal_esp32 || true

    - name: Run integration tests
      run: cargo test --test integration_tests -- --nocapture