name: Deploy WASM to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'ui-frontend/**'
      - '.github/workflows/deploy-pages.yml'

jobs:
  build-and-deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # SHA: 2b2e6c4b0e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable # SHA: c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3

      - name: Install wasm-pack
        run: cargo install wasm-pack --locked

      - name: Build WASM package
        run: wasm-pack build ./ui-frontend --target web --out-dir ./ui-frontend/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # SHA: d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui-frontend/dist
          # Volitelné: commit zpráva
          commit_message: 'deploy: auto-deploy WASM UI to gh-pages' 