name: Publish Docker image to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # SHA: 2b2e6c4b0e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 # SHA: 9c9c9c9c9c9c9c9c9c9c9c9c9c9c9c9c9c9c9c9c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5 # SHA: a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # SHA: b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 